version: "2"
services:
    mongo:
        image: mongo
        ports:
          - "27017:27017"
    api:
        build: ../PortalApi
        depends_on:
          - mongo
        ports:
          - "7000:7000"
        environment:
          - MONGO_HOST=mongo
          - MONGO_PORT=27017
          - MONGO_DB_NAME=bitguild
        volumes:
          - ../PortalApi:/app
          - /app/node_modules
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - mongo
            - api
