version: "2"
services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
        volumes:
          - ./tmp/pgdata:/var/lib/postgresql/data
    api:
        build:
            context: ../PortalApi
            args:
                NODE_ENV: development
        command: yarnpkg run dev
        ports:
            - "7000:7000"
        volumes:
            - ../PortalApi:/app
            - /app/node_modules
        environment:
            PORT: 7000
            PG_HOST: postgres
            PG_PORT: 5432
            PG_USER: postgres
            PG_PASS: password
            PG_DB: postgres
            WS_GETH_SERVER: ws://docker.for.mac.localhost:8546
        depends_on:
            - postgres
    web:
        build:
            context: .
            args:
                NODE_ENV: development
        command: node server.js
        ports:
            - "5000:5000"
        environment:
            - NODE_ENV=development
            - DEPLOYED_ENV=local
            - PORT=5000
            - RENDERING=server
            - GOOGLE_ANALYTICS_TRACKING_ID=UA-114789298-2
            - MAINNET_TOKEN_CONTRACT_ADDR=0x7E43581b19ab509BCF9397a2eFd1ab10233f27dE
            - MAINNET_TOPUP_CONTRACT_ADDR=0xb3bbc0cc040413a3e68dcaa8f2b6eac2957c5ce0
            - MAINNET_ORACLE_CONTRACT_ADDR=0x3127be52acba38beab6b4b3a406dc04e557c037c
            - RINKEBY_TOKEN_CONTRACT_ADDR=0x0f2698b7605fe937933538387b3d6fec9211477d
            - RINKEBY_TOPUP_CONTRACT_ADDR=0xcc963489d579856b783f2f242af19a32b488b3ea
            - RINKEBY_ORACLE_CONTRACT_ADDR=0x20159d575724b68d8a1a80e16fcb874883329114
            - RINKEBY_BITIZENS_IGO_CONTRACT_ADDR=0xbCb371139215d4a6dFB86Ef0F9376d9505780945
            - MAINNET_BITIZENS_IGO_CONTRACT_ADDR=0xF4bac3A3aa5Ff583a3e0D1e2e511979901C1a4A8
            - MAINNET_MARKETPLACE_CONTRACT_ADDR=0x123456
            - RINKEBY_MARKETPLACE_CONTRACT_ADDR=0x1062e88cea36123c9913acfda367dc3d7e480b1e
            - SENDBIRD_APP_ID=BB1E0777-B8CE-44DF-BA37-63EBA2E858F1
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - postgres
            - api
