version: "2"
services:
    mongo:
        image: mongo
        ports:
          - "27017:27017"
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: password
        volumes:
          - ./tmp/pgdata:/var/lib/postgresql/data
    api:
        build:
            context: ../PortalApi
            args:
                NODE_ENV: development
        command: node_modules/.bin/nodemon server/server.js --exec babel-node
        depends_on:
          - mongo
        ports:
          - "7000:7000"
        environment:
          - NODE_ENV=development
          - MONGO_URL=mongodb://mongo:27017/bitguild
        volumes:
          - ../PortalApi:/app
          - /app/node_modules
    gql:
        build:
            context: ../../oss/folieadeux
            args:
                NODE_ENV: development
        command: yarnpkg run dev
        ports:
            - "4000:4000"
        volumes:
            - ../../oss/folieadeux:/app
            - /app/node_modules
        environment:
            PG_HOST: postgres
            PG_PORT: 5432
            PG_USER: postgres
            PG_PASS: password
            PG_DB: postgres
        depends_on:
            - postgres
    web:
        build:
            context: .
            args:
                NODE_ENV: development
        command: node_modules/.bin/babel-node server/server.js
        ports:
            - "5000:5000"
        environment:
            - NODE_ENV=development
            - RENDERING=server
            - GOOGLE_ANALYTICS_TRACKING_ID=UA-114789298-2
            - MAINNET_TOKEN_CONTRACT_ADDR=0x7E43581b19ab509BCF9397a2eFd1ab10233f27dE
            - MAINNET_TOPUP_CONTRACT_ADDR=0xb3bbc0cc040413a3e68dcaa8f2b6eac2957c5ce0
            - MAINNET_ORACLE_CONTRACT_ADDR=0x3127be52acba38beab6b4b3a406dc04e557c037c
            - RINKEBY_TOKEN_CONTRACT_ADDR=0x0f2698b7605fe937933538387b3d6fec9211477d
            - RINKEBY_TOPUP_CONTRACT_ADDR=0xcc963489d579856b783f2f242af19a32b488b3ea
            - RINKEBY_ORACLE_CONTRACT_ADDR=0x20159d575724b68d8a1a80e16fcb874883329114
            - SENDBIRD_APP_ID=BB1E0777-B8CE-44DF-BA37-63EBA2E858F1
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - mongo
            - postgres
            - api
            - gql
