export const APP_INIT = "APP_INIT";
export const APP_RESIZE = "APP_RESIZE";

export const GA_CREATE = "GA_CREATE";

export const PRESALE_TRANSACTIONS_CHANGED = "PRESALE_TRANSACTIONS_CHANGED";

export const MESSAGE_ADD = "MESSAGE_ADD";
export const MESSAGE_ADD_ALL = "MESSAGE_ADD_ALL";
export const MESSAGE_REMOVE = "MESSAGE_REMOVE";
export const MESSAGE_REMOVE_ALL = "MESSAGE_REMOVE_ALL";

export const VALIDATION_ADD = "VALIDATION_ADD";
export const VALIDATION_ADD_ALL = "VALIDATION_ADD_ALL";
export const VALIDATION_REMOVE = "VALIDATION_REMOVE";
export const VALIDATION_REMOVE_ALL = "VALIDATION_REMOVE_ALL";

export const USER_LOADING = "USER_LOADING";
export const USER_CHANGED = "USER_CHANGED";
export const USER_ERROR = "USER_ERROR";
export const USER_RESET = "USER_RESET";
export const USER_SHOW_REGISTER_WORKFLOW = "USER_SHOW_REGISTER_WORKFLOW";
export const SHOW_CONVERT_MODAL = "SHOW_CONVERT_MODAL";

export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";


export const NETWORK_NEW_BLOCK = "NETWORK_NEW_BLOCK";
export const NETWORK_CHANGED = "NETWORK_CHANGED";
export const NETWORK_LOADING = "NETWORK_LOADING";
export const NETWORK_ERROR = "NETWORK_ERROR";
export const NETWORK_GET = "NETWORK_GET";
export const NETWORK_AVAILABLE = "NETWORK_AVAILABLE";
export const NETWORK_ACCOUNT_LOGGED_OUT = "NETWORK_ACCOUNT_LOGGED_OUT";
export const NETWORK_BEGIN_LISTENING = "NETWORK_BEGIN_LISTENING";
export const NETWORK_GET_AVAILABILITY = "NETWORK_GET_AVAILABILITY";
export const NETWORK_GET_BALANCE_ETH = "NETWORK_GET_BALANCE_ETH";
export const NETWORK_GET_BALANCE_PLAT = "NETWORK_GET_BALANCE_PLAT";

export const ACCOUNT_INIT = "ACCOUNT_INIT";
export const ACCOUNT_CHANGED = "ACCOUNT_CHANGED";
export const ACCOUNT_ERROR = "ACCOUNT_ERROR";
export const ACCOUNT_RESET = "ACCOUNT_RESET";
export const ACCOUNT_SIGN_OUT = "ACCOUNT_SIGN_OUT";
export const ACCOUNT_GET = "ACCOUNT_GET";
export const ACCOUNT_LOGGED_IN = "ACCOUNT_LOGGED_IN";
export const ACCOUNT_LOGGED_OUT = "ACCOUNT_LOGGED_OUT";
export const ACCOUNT_BEGIN_POLLING = "ACCOUNT_BEGIN_POLLING";
export const ACCOUNT_POLL = "ACCOUNT_POLL";

export const BALANCE_ETH_LOADING = "BALANCE_ETH_LOADING";
export const BALANCE_ETH_CHANGED = "BALANCE_ETH_CHANGED";
export const BALANCE_ETH_ERROR = "BALANCE_ETH_ERROR";
export const BALANCE_ETH_RESET = "BALANCE_ETH_RESET";

export const BALANCE_PLAT_LOADING = "BALANCE_PLAT_LOADING";
export const BALANCE_PLAT_CHANGED = "BALANCE_PLAT_CHANGED";
export const BALANCE_PLAT_ERROR = "BALANCE_PLAT_ERROR";
export const BALANCE_PLAT_RESET = "BALANCE_PLAT_RESET";

export const INVENTORY_ITEMS_REQUEST = "INVENTORY_ITEMS_REQUEST";
export const INVENTORY_ITEMS_LOADING = "INVENTORY_ITEMS_LOADING";
export const INVENTORY_ITEMS_CHANGED = "INVENTORY_ITEMS_CHANGED";
export const INVENTORY_ITEMS_ERROR = "INVENTORY_ITEMS_ERROR";

export const RATE_REQUEST = "RATE_REQUEST";
export const RATE_CHANGED = "RATE_CHANGED";
export const RATE_ERROR = "RATE_ERROR";
export const RATE_LOADING = "RATE_LOADING";

export const SENDBIRD_INIT = "SENDBIRD_INIT";
export const CHAT_INIT = "CHAT_INIT";
export const CHAT_LOAD_MESSAGES = "CHAT_LOAD_MESSAGES";
export const CHAT_MESSAGE_RECEIVED = "CHAT_MESSAGE_RECEIVED";
export const CHAT_MESSAGE_SEND = "CHAT_MESSAGE_SEND";
export const CHAT_MESSAGE_SENT = "CHAT_MESSAGE_SENT";
export const CHAT_SET_CHANNEL = "CHAT_SET_CHANNEL";
export const CHAT_RECEIVE_MESSAGE = "CHAT_RECEIVE_MESSAGE";
export const CHAT_TOGGLE = "CHAT_TOGGLE";
export const GLOBAL_HANDLER = "GLOBAL_HANDLER";

export const MENU_SHOW = "MENU_SHOW";

export const GAME_REQUEST = "GAME_REQUEST";
export const GAME_LOADING = "GAME_LOADING";
export const GAME_CHANGED = "GAME_CHANGED";
export const GAME_ERROR = "GAME_ERROR";

export const GAMES_REQUEST = "GAMES_REQUEST";
export const GAMES_LOADING = "GAMES_LOADING";
export const GAMES_CHANGED = "GAMES_CHANGED";
export const GAMES_ERROR = "GAMES_ERROR";

export const GIFT_ADD_LOADING = "GIFT_ADD_LOADING";
export const GIFT_ADD_SUCCESS = "GIFT_ADD_SUCCESS";
export const GIFT_ADD_ERROR = "GIFT_ADD_ERROR";
export const GIFT_REMOVE_LOADING = "GIFT_REMOVE_LOADING";
export const GIFT_REMOVE_SUCCESS = "GIFT_REMOVE_SUCCESS";
export const GIFT_REMOVE_ERROR = "GIFT_REMOVE_ERROR";

export const GAS_LOADING = "GAS_LOADING";
export const GAS_CHANGED = "GAS_CHANGED";
export const GAS_ERROR = "GAS_ERROR";
