export const MESSAGE_ADD = "MESSAGE_ADD";
export const MESSAGE_ADD_ALL = "MESSAGE_ADD_ALL";
export const MESSAGE_REMOVE = "MESSAGE_REMOVE";
export const MESSAGE_REMOVE_ALL = "MESSAGE_REMOVE_ALL";

export const USER_LOADING = "USER_LOADING";
export const USER_CHANGED = "USER_CHANGED";
export const USER_ERROR = "USER_ERROR";

export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";

export const ACCOUNT_CHANGED = "ACCOUNT_CHANGED";
export const ACCOUNT_ERROR = "ACCOUNT_ERROR";

export const NEW_BLOCK = "NEW_BLOCK";

export const NETWORK_CHANGED = "NETWORK_CHANGED";
export const NETWORK_LOADING = "NETWORK_LOADING";
export const NETWORK_ERROR = "NETWORK_ERROR";

export const BALANCE_ETH_LOADING = "BALANCE_ETH_LOADING";
export const BALANCE_ETH_CHANGED = "BALANCE_ETH_CHANGED";
export const BALANCE_ETH_ERROR = "BALANCE_ETH_ERROR";

export const BALANCE_PLAT_LOADING = "BALANCE_PLAT_LOADING";
export const BALANCE_PLAT_CHANGED = "BALANCE_PLAT_CHANGED";
export const BALANCE_PLAT_ERROR = "BALANCE_PLAT_ERROR";

export const INVENTORY_GAMES_REQUEST = "INVENTORY_GAMES_REQUEST";
export const INVENTORY_GAMES_LOADING = "INVENTORY_GAMES_LOADING";
export const INVENTORY_GAMES_CHANGED = "INVENTORY_GAMES_CHANGED";
export const INVENTORY_GAMES_ERROR = "INVENTORY_GAMES_ERROR";

export const INVENTORY_ITEMS_REQUEST = "INVENTORY_ITEMS_REQUEST";
export const INVENTORY_ITEMS_LOADING = "INVENTORY_ITEMS_LOADING";
export const INVENTORY_ITEMS_CHANGED = "INVENTORY_ITEMS_CHANGED";
export const INVENTORY_ITEMS_ERROR = "INVENTORY_ITEMS_ERROR";

export const RATE_REQUEST = "RATE_REQUEST";
export const RATE_CHANGED = "RATE_CHANGED";
export const RATE_ERROR = "RATE_ERROR";
export const RATE_LOADING = "RATE_LOADING";

export const CHAT_INIT = "CHAT_INIT";
export const CHAT_LOAD_MESSAGES = "CHAT_LOAD_MESSAGES";
export const CHAT_MESSAGE_RECEIVED = "CHAT_MESSAGE_RECEIVED";
export const CHAT_MESSAGE_SEND = "CHAT_MESSAGE_SEND";
export const CHAT_MESSAGE_SENT = "CHAT_MESSAGE_SENT";
export const CHAT_SET_CHANNEL = "CHAT_SET_CHANNEL";
export const CHAT_RECEIVE_MESSAGE = "CHAT_RECEIVE_MESSAGE";

export const GAME_REQUEST = "GAME_REQUEST";
export const GAME_LOADING = "GAME_LOADING";
export const GAME_CHANGED = "GAME_CHANGED";
export const GAME_ERROR = "GAME_ERROR";

export const GIFT_LOADING = "GIFT_LOADING";
export const GIFT_CHANGED = "GIFT_CHANGED";
export const GIFT_ERROR = "GIFT_ERROR";
