export const MESSAGE_ADD = "MESSAGE_ADD";
export const MESSAGE_ADD_ALL = "MESSAGE_ADD_ALL";
export const MESSAGE_REMOVE = "MESSAGE_REMOVE";
export const MESSAGE_REMOVE_ALL = "MESSAGE_REMOVE_ALL";

export const SWITCH_LANGUAGE = "SWITCH_LANGUAGE";

export const USER_LOADING = "USER_LOADING";
export const USER_CHANGED = "USER_CHANGED";
export const USER_ERROR = "USER_ERROR";

export const CREATE_USER = "CREATE_USER";
export const CHANGE_ACCOUNT = "CHANGE_ACCOUNT";

export const NEW_BLOCK = "NEW_BLOCK";

export const BALANCE_ETH_LOADING = "BALANCE_ETH_LOADING";
export const BALANCE_ETH_CHANGED = "BALANCE_ETH_CHANGED";
export const BALANCE_ETH_ERROR = "BALANCE_ETH_ERROR";

export const BALANCE_PLAT_LOADING = "BALANCE_PLAT_LOADING";
export const BALANCE_PLAT_CHANGED = "BALANCE_PLAT_CHANGED";
export const BALANCE_PLAT_ERROR = "BALANCE_PLAT_ERROR";

export const INVENTORY_CHANGED = "INVENTORY_CHANGED";
export const INVENTORY_ERROR = "INVENTORY_ERROR";
export const INVENTORY_LOADING = "INVENTORY_LOADING";
